version: '3.9'

services:
  aggregatron-db:
    image: postgres
    container_name: aggregatron-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER}'"]
      interval: 5s
      timeout: 30s
      retries: 5
  
  aggregatron-api-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: aggregatron-api-server
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    depends_on:
      aggregatron-db:
        condition: service_healthy
